-- =========================
-- COUNTIES
-- =========================
CREATE TABLE Counties (
    CountyId NUMBER GENERATED BY DEFAULT AS IDENTITY,
    Name NVARCHAR2(100) NOT NULL,
    Region NVARCHAR2(80) NOT NULL,
    Headquarters NVARCHAR2(80) NOT NULL,
    PopulationEstimate NUMBER NOT NULL,
    AreaSqKm NUMBER(10,1) NOT NULL,
    EcosystemFocus NVARCHAR2(120) NOT NULL,
    RiskLevel NVARCHAR2(20) NOT NULL,
    Overview NVARCHAR2(500) NOT NULL,
    ContactPhone NVARCHAR2(40) NOT NULL,
    ContactEmail NVARCHAR2(120) NOT NULL,

    CONSTRAINT PK_Counties PRIMARY KEY (CountyId),
    CONSTRAINT UQ_Counties_Name UNIQUE (Name),
    CONSTRAINT CHK_Counties_RiskLevel CHECK (RiskLevel IN ('Low','Medium','High'))
);

-- =========================
-- RESPONSE LOCATIONS
-- =========================
CREATE TABLE ResponseLocations (
    ResponseLocationId NUMBER GENERATED BY DEFAULT AS IDENTITY,
    LocationName NVARCHAR2(140) NOT NULL,
    LocationType NVARCHAR2(60) NOT NULL,
    CountyId NUMBER,
    Headquarters NVARCHAR2(80) NOT NULL,
    FocusArea NVARCHAR2(180) NOT NULL,
    ContactPhone NVARCHAR2(40) NOT NULL,
    ContactEmail NVARCHAR2(120) NOT NULL,

    CONSTRAINT PK_ResponseLocations PRIMARY KEY (ResponseLocationId),
    CONSTRAINT FK_ResponseLocations_County 
        FOREIGN KEY (CountyId) REFERENCES Counties(CountyId)
);

-- =========================
-- SERVICES
-- =========================
CREATE TABLE Services (
    ServiceId NUMBER GENERATED BY DEFAULT AS IDENTITY,
    Title NVARCHAR2(120) NOT NULL,
    Description NVARCHAR2(280) NOT NULL,
    Controller NVARCHAR2(60) NOT NULL,
    Action NVARCHAR2(60) NOT NULL,
    SearchTerm NVARCHAR2(100),
    SortOrder NUMBER NOT NULL,

    CONSTRAINT PK_Services PRIMARY KEY (ServiceId)
);

-- =========================
-- ADMIN USERS
-- =========================
CREATE TABLE AdminUsers (
    AdminUserId NUMBER GENERATED BY DEFAULT AS IDENTITY,
    FullName NVARCHAR2(120) NOT NULL,
    Username NVARCHAR2(60) NOT NULL,
    Email NVARCHAR2(120) NOT NULL,
    PasswordHash NVARCHAR2(255) NOT NULL,
    RoleName NVARCHAR2(60) NOT NULL,
    IsActive NUMBER(1) DEFAULT 1 NOT NULL,
    LastLoginAt TIMESTAMP,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT PK_AdminUsers PRIMARY KEY (AdminUserId),
    CONSTRAINT UQ_AdminUsers_Username UNIQUE (Username),
    CONSTRAINT UQ_AdminUsers_Email UNIQUE (Email),
    CONSTRAINT CHK_AdminUsers_IsActive CHECK (IsActive IN (0,1))
);

-- =========================
-- ADMIN ACTIVITY LOG
-- =========================
CREATE TABLE AdminActivityLog (
    ActivityLogId NUMBER GENERATED BY DEFAULT AS IDENTITY,
    AdminUserId NUMBER NOT NULL,
    ActivityType NVARCHAR2(80) NOT NULL,
    EntityType NVARCHAR2(80) NOT NULL,
    EntityId NUMBER,
    Description NVARCHAR2(320) NOT NULL,
    IpAddress NVARCHAR2(64),
    OccurredAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT PK_AdminActivityLog PRIMARY KEY (ActivityLogId),
    CONSTRAINT FK_AdminActivityLog_User 
        FOREIGN KEY (AdminUserId) REFERENCES AdminUsers(AdminUserId)
);

-- =========================
-- LICENSING SERVICES
-- =========================
CREATE TABLE LicensingServices (
    LicenseServiceId NUMBER GENERATED BY DEFAULT AS IDENTITY,
    CountyId NUMBER,
    Title NVARCHAR2(160) NOT NULL,
    Category NVARCHAR2(80) NOT NULL,
    ProcessingWindowDays NUMBER NOT NULL,
    FeeKsh NUMBER(12,2) NOT NULL,
    AppliesTo NVARCHAR2(180) NOT NULL,
    Summary NVARCHAR2(450) NOT NULL,
    Requirements NVARCHAR2(500) NOT NULL,
    IsFeatured NUMBER(1) DEFAULT 0 NOT NULL,
    SortOrder NUMBER NOT NULL,

    CONSTRAINT PK_LicensingServices PRIMARY KEY (LicenseServiceId),
    CONSTRAINT FK_LicensingServices_County 
        FOREIGN KEY (CountyId) REFERENCES Counties(CountyId),
    CONSTRAINT CHK_Licensing_IsFeatured CHECK (IsFeatured IN (0,1))
);

-- =========================
-- UPDATES
-- =========================
CREATE TABLE Updates (
    UpdateId NUMBER GENERATED BY DEFAULT AS IDENTITY,
    CountyId NUMBER,
    Title NVARCHAR2(180) NOT NULL,
    Summary NVARCHAR2(400) NOT NULL,
    PublishDate DATE NOT NULL,
    Category NVARCHAR2(60) NOT NULL,
    IsFeatured NUMBER(1) DEFAULT 0 NOT NULL,

    CONSTRAINT PK_Updates PRIMARY KEY (UpdateId),
    CONSTRAINT FK_Updates_County 
        FOREIGN KEY (CountyId) REFERENCES Counties(CountyId),
    CONSTRAINT CHK_Updates_IsFeatured CHECK (IsFeatured IN (0,1))
);

-- =========================
-- PROGRAMS
-- =========================
CREATE TABLE Programs (
    ProgramId NUMBER GENERATED BY DEFAULT AS IDENTITY,
    CountyId NUMBER NOT NULL,
    Title NVARCHAR2(160) NOT NULL,
    Status NVARCHAR2(30) NOT NULL,
    BudgetMillions NUMBER(10,1) NOT NULL,
    Beneficiaries NUMBER NOT NULL,
    Summary NVARCHAR2(450) NOT NULL,

    CONSTRAINT PK_Programs PRIMARY KEY (ProgramId),
    CONSTRAINT FK_Programs_County 
        FOREIGN KEY (CountyId) REFERENCES Counties(CountyId)
);

-- =========================
-- RESEARCH ACTIVITIES
-- =========================
CREATE TABLE ResearchActivities (
    ResearchActivityId NUMBER GENERATED BY DEFAULT AS IDENTITY,
    CountyId NUMBER,
    Title NVARCHAR2(180) NOT NULL,
    ResearchTheme NVARCHAR2(90) NOT NULL,
    Status NVARCHAR2(30) NOT NULL,
    LeadOffice NVARCHAR2(140) NOT NULL,
    StartDate DATE NOT NULL,
    Summary NVARCHAR2(450) NOT NULL,
    Outputs NVARCHAR2(240) NOT NULL,
    IsFeatured NUMBER(1) DEFAULT 0 NOT NULL,

    CONSTRAINT PK_ResearchActivities PRIMARY KEY (ResearchActivityId),
    CONSTRAINT FK_ResearchActivities_County 
        FOREIGN KEY (CountyId) REFERENCES Counties(CountyId),
    CONSTRAINT CHK_Research_IsFeatured CHECK (IsFeatured IN (0,1))
);

-- =========================
-- LICENSE APPLICATIONS
-- =========================
CREATE TABLE LicenseApplications (
    ApplicationId NUMBER GENERATED BY DEFAULT AS IDENTITY,
    LicenseServiceId NUMBER NOT NULL,
    ProjectCountyId NUMBER,
    ApplicantName NVARCHAR2(120) NOT NULL,
    ApplicantEmail NVARCHAR2(120) NOT NULL,
    OrganizationName NVARCHAR2(160),
    ProjectLocation NVARCHAR2(180) NOT NULL,
    ProjectSummary NVARCHAR2(1200) NOT NULL,
    SupportingDocuments NVARCHAR2(500) NOT NULL,
    Status NVARCHAR2(30) NOT NULL,
    ReviewNotes NVARCHAR2(500),
    ReviewedAt TIMESTAMP,
    SubmittedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT PK_LicenseApplications PRIMARY KEY (ApplicationId),
    CONSTRAINT FK_LicenseApplications_Service 
        FOREIGN KEY (LicenseServiceId) REFERENCES LicensingServices(LicenseServiceId),
    CONSTRAINT FK_LicenseApplications_County 
        FOREIGN KEY (ProjectCountyId) REFERENCES Counties(CountyId)
);

-- =========================
-- INCIDENT REPORTS
-- =========================
CREATE TABLE IncidentReports (
    ReportId NUMBER GENERATED BY DEFAULT AS IDENTITY,
    ReporterName NVARCHAR2(80) NOT NULL,
    ReporterEmail NVARCHAR2(120) NOT NULL,
    CountyId NUMBER,
    ResponseLocationId NUMBER NOT NULL,
    Category NVARCHAR2(60) NOT NULL,
    Location NVARCHAR2(120) NOT NULL,
    Description NVARCHAR2(1200) NOT NULL,
    Status NVARCHAR2(30) NOT NULL,
    ReviewNotes NVARCHAR2(500),
    UpdatedAt TIMESTAMP,
    ReportedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT PK_IncidentReports PRIMARY KEY (ReportId),
    CONSTRAINT FK_IncidentReports_County 
        FOREIGN KEY (CountyId) REFERENCES Counties(CountyId),
    CONSTRAINT FK_IncidentReports_ResponseLocation 
        FOREIGN KEY (ResponseLocationId) REFERENCES ResponseLocations(ResponseLocationId)
);

-- =========================
-- KNOWLEDGE DOCUMENTS
-- =========================
CREATE TABLE KnowledgeDocuments (
    DocumentId NUMBER GENERATED BY DEFAULT AS IDENTITY,
    SourceType NVARCHAR2(60) NOT NULL,
    SourceRecordId NUMBER NOT NULL,
    CountyId NUMBER,
    Category NVARCHAR2(90) NOT NULL,
    Title NVARCHAR2(180) NOT NULL,
    Summary NVARCHAR2(500) NOT NULL,
    RouteEndpoint NVARCHAR2(60) NOT NULL,
    RouteRecordId NUMBER,
    NormalizedText NVARCHAR2(2000) NOT NULL,
    TokenCount NUMBER NOT NULL,
    IndexedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT PK_KnowledgeDocuments PRIMARY KEY (DocumentId),
    CONSTRAINT UQ_KnowledgeDocuments UNIQUE (SourceType, SourceRecordId),
    CONSTRAINT FK_KnowledgeDocuments_County 
        FOREIGN KEY (CountyId) REFERENCES Counties(CountyId)
);

-- =========================
-- STOP WORDS
-- =========================
CREATE TABLE KnowledgeStopWords (
    Word VARCHAR2(40),

    CONSTRAINT PK_KnowledgeStopWords PRIMARY KEY (Word)
);

-- =========================
-- VECTOR INDEX
-- =========================
CREATE TABLE KnowledgeVectorIndex (
    DocumentId NUMBER NOT NULL,
    DimensionNumber NUMBER NOT NULL,
    DimensionValue FLOAT NOT NULL,

    CONSTRAINT PK_KnowledgeVectorIndex
        PRIMARY KEY (DocumentId, DimensionNumber),
    CONSTRAINT FK_KnowledgeVectorIndex_Doc 
        FOREIGN KEY (DocumentId) REFERENCES KnowledgeDocuments(DocumentId)
); 
CREATE INDEX IX_KnowledgeDocuments_Category ON KnowledgeDocuments(Category, CountyId);
CREATE INDEX IX_KnowledgeVectorIndex_Dimension ON KnowledgeVectorIndex(DimensionNumber, DocumentId, DimensionValue);
CREATE INDEX IX_AdminActivityLog_OccurredAt ON AdminActivityLog(OccurredAt DESC, AdminUserId, ActivityType, EntityType);
CREATE INDEX IX_IncidentReports_Status ON IncidentReports(Status, ReportedAt DESC, CountyId, ResponseLocationId);
CREATE INDEX IX_LicenseApplications_Status ON LicenseApplications(Status, SubmittedAt DESC, LicenseServiceId, ProjectCountyId);